<?php
if (!$routes_data = getenv('PLATFORM_ROUTES')) {
  exit('env:PLATFORM_ROUTES not found.');
}

$routes = json_decode(base64_decode($routes_data));

if (!$routes) {
  exit('Error decoding env:PLATFORM_ROUTES.');
}

foreach ($routes as $route_uri => $route) {
  if ($route->primary) {
    $primary_route = $route_uri;
    break;
  }
}

if (empty($primary_route)) {
  exit('No primary route found.');
}

echo <<<EOL
# Drush configuration file.
# This was automatically generated by the script:
# https://github.com/ilrWebServices/platformsh_generate_drush_yml/blob/main/platformsh_generate_drush_yml.php

options:
  # Set the default site URL.
  uri: "$primary_route"

EOL;

exit(0);
